trigger:
- master

pool:
  vmImage: 'macOS-13'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.17.0'
  displayName: 'Install Node.js'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'final3.mobileprovision'
  displayName: 'Installation Provisioning Profile'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates.p12'
    certPwd: 'Yuzee@98933'
    keychain: 'temp'


    
- script: |
    rm -rf $BUILD_WORKINGDIRECTORY/node_modules
  displayName: 'delete node_modules'

- script: |
    npm cache clean --force
    npm install --legacy-peer-deps
    npm install -g @angular/cli@10.0.7
    npm i @auth0/angular-jwt@5.0.2 --legacy-peer-deps
  displayName: 'npm install and build'

- script: |
    npm install -g cordova
    npm install -g @ionic/cli
  displayName: 'Installation of Ionic Cli and Cardova'

  
- script: |
    ionic cordova platform rm ios
    ionic cordova platform add ios
    
  displayName: 'Adding platform IOS'


- script: |
    ionic cordova build ios --prod --release
  displayName: 'building ios'

- script: /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(Build.BuildId)" "$(Build.SourcesDirectory)/platforms/ios/Yuzee/Yuzee-Info.plist"
  displayName: Update Build Number

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Yuzee'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/Yuzee.xcworkspace'
    xcodeVersion: 'default'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'


- task: CopyFiles@2
  inputs:
    #SourceFolder: '$(Agent.WorkFolder)'
    Contents: '**/*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    preserveTimestamp: true
    #flattenFolders: true
  displayName: 'Copying IOS IPA as Artifact'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Yuzee-ios'
    artifactType: 'container'  

- task: DownloadBuildArtifacts@0
  displayName: 'Download artifacts'
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    downloadPath: 'releases_drop'
    
- task: AppStoreRelease@1
  inputs:
    authType: 'ApiKey'
    apiKeyId: 'FRQ3946A3S'
    apiKeyIssuerId: '69a6de85-b38e-47e3-e053-5b8c7c11a4d1'
    apitoken: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ00vZFh3dkxWcU9CQXp4T1IKb0ptK1dQVmJpYzRuTFJmY0Ntb3R6L2xTYm1XZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTcEk3azdJcTdhY2xZOApLbWF5cmh2K1FLV0dXOGRtU2dQMUsza1k5aHJsQ3pweXhPMFU3WGN5M1hSYlFobjVQNFk0VXd2bWdUNHpla0F4CjZVcXlyVUovCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0='
    releaseTrack: 'TestFlight'
    appIdentifier: 'com.yuzee.test'
    appType: 'iOS'
    ipaPath: 'releases_drop/Yuzee-ios/output/$(SDK)/$(Configuration)/*.ipa'
    shouldSkipWaitingForProcessing: true
    shouldSkipSubmission: true
    appSpecificId: '1621166360'

- script: |
    brew install findutils
    alias find=gfind
    mkdir artifact-ios
    find . -name "*.ipa" -type f -exec cp {} ./artifact-ios \;
    echo "$(ls -la)"
    brew install rclone 
    rclone --config="root/.config/rclone/rclone.conf" config file
    rclone --config="root/.config/rclone/rclone.conf" copy artifact-ios/*.ipa onedrive:IOS-Builds