import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { CKEditorModule } from 'ckeditor4-angular';
import { Ng2SearchPipeModule } from 'ng2-search-filter';
import { BarRatingModule } from 'ngx-bar-rating';
import { YuzeeCommonModule } from 'yuzee-shared-lib';
import { IonicModule } from '@ionic/angular';
import {
  TranslateLoader,
  TranslateModule,
} from '@ngx-translate/core';
import { setTranslateLoader } from '../app.module';
import {
  BlockCopyPasteDirective,
  BoldPipe,
  InputNumberValidation,
  LongPressDirective,
  ShortNumberPipe,
  WhiteSpaceRestrictionDirective,

} from '../library';
import { CDVPhotoLibraryPipe } from '../library/pipes/cdv-photo-library.pipe';
import { AppSharedLibraryModule } from '../library/shared-library.module';
import * as COMPONENT from './';
import { Autosize } from './';
import { LocationEditPage } from './company-institute-school/components/location/location-edit/location-edit.page';
import { ChangeRequestModalComponent } from './company-institute-school/components/change-request-modal/change-request-modal.component';
import { CustomPipesModule } from '../library/pipes/custom-pipes.module';

@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule,
    BarRatingModule,
    AppSharedLibraryModule,
    CKEditorModule,
    Ng2SearchPipeModule,
    TranslateModule.forChild({
      loader: {
        provide: TranslateLoader,
        useFactory: setTranslateLoader,
        deps: [HttpClient],
      },
    }),
    FormsModule,
    CustomPipesModule,
  ],
  declarations: [
    BoldPipe,
    ShortNumberPipe,
    LongPressDirective,
    WhiteSpaceRestrictionDirective,
    BlockCopyPasteDirective,
    InputNumberValidation,
    Autosize,
    CDVPhotoLibraryPipe,
    COMPONENT.ProviderCodeComponent,
    // Generic Components
    COMPONENT.HeaderHomeComponent,
    COMPONENT.DurationFilterComponent,
    COMPONENT.CcFormLogoSlideComponent,
    LocationEditPage,
    COMPONENT.ContactdetailsComponent,
    COMPONENT.VideosComponent,
    ChangeRequestModalComponent,
    COMPONENT.CcFormFinalSlideComponent,
    COMPONENT.CcWorkingHoursComponent,
    COMPONENT.CompanyProfileVerificationComponent,
    COMPONENT.GenericSingleSelectSearchComponent,
    COMPONENT.GenericBackConfirmationComponent,
    COMPONENT.GenericDescriptionComponent,
    COMPONENT.GenericDeleteConfirmationComponent,
    COMPONENT.GenericIonSearchbarComponent,
    COMPONENT.GenericSearchableRadioSelectionComponent,
    COMPONENT.EditCoverPhotoComponent,
    COMPONENT.EditProfilePhotoComponent,
    COMPONENT.PeopleMayYouKnowComponent,
    COMPONENT.LevelListMultipleComponent,
    COMPONENT.GalleryComponent,
    COMPONENT.CommentsComponent,
    COMPONENT.ViewImageComponent,
    COMPONENT.HeaderComponent,
    COMPONENT.InterestedHobbiesEditComponent,
    COMPONENT.SkillsListComponent,
    COMPONENT.SliderScreensComponent,
    COMPONENT.LocationAutocompleteComponent,
    COMPONENT.PhoneCodePickerComponent,
    COMPONENT.PhoneCodePickerSelectorComponent,
    COMPONENT.ReadAllReviewComponent,
    COMPONENT.WriteAReviewComponent,
    COMPONENT.WriteAReviewNextComponent,
    COMPONENT.AnyDateDaysComponent,
    COMPONENT.AccordionsComponent,
    COMPONENT.PopupsSkeltonLoadersComponent,
    COMPONENT.RatingStarsComponent,
    COMPONENT.CourseCardComponent,
    COMPONENT.CoursesCardsComponent,
    COMPONENT.ScholarshipsCardsComponent,
    COMPONENT.CompanyCardsComponent,
    COMPONENT.DocumentsComponent,
    COMPONENT.UsersRecommendationsComponent,
    COMPONENT.UserFindMeComponent,
    COMPONENT.NearestCourseMapComponent,
    COMPONENT.MapViewCourseComponent,
    COMPONENT.MapViewListComponent,
    COMPONENT.EstimateCostLivingComponent,
    COMPONENT.MapViewComponent,
    COMPONENT.PriceSummaryComponent,
    COMPONENT.DayOfWeekComponent,
    COMPONENT.VideoFullViewComponent,
    COMPONENT.AddToProfileComponent,
    COMPONENT.AddToProfileItemComponent,
    COMPONENT.SeeMoreParaComponent,
    COMPONENT.AssociatedAuthorsInfoComponent,
    COMPONENT.EditEnglishQualificationComponent,
    COMPONENT.DeleteEditItemComponent,
    COMPONENT.ProfileStatusModalComponent,
    COMPONENT.AboutusComponent,
    COMPONENT.PickInstitutionCompanyComponent,
    COMPONENT.CreateCompanyInstituteInfoComponent,
    COMPONENT.CourseInfoPopupComponent,
    // Off Campus
    // Customize Gallery
    COMPONENT.LoadGalleryComponent,
    COMPONENT.GenericCourseSearchMultipleComponent,
    COMPONENT.GenericFacultySearchMultipleComponent,
    COMPONENT.GenderCommonDropdownComponent,
    COMPONENT.GenericDescriptionComponent,
    COMPONENT.GenericIonSearchbarComponent,
    COMPONENT.GenericMultiSearchableRadioSelectionComponent,
    COMPONENT.UsersComponent,
    COMPONENT.SideInfoCardsComponent,
    // PROFILE SHARED COMPONENTS
    COMPONENT.ProfileHeaderComponent,
    COMPONENT.ProfileVideosComponent,
    COMPONENT.ProfileStatusComponent,
    COMPONENT.ProfileInfoWrapSliderComponent,
    COMPONENT.ProfileAddToProfileComponent,
    COMPONENT.ProfileContactDetailsComponent,
    COMPONENT.EditProfileContactDetailsComponent,
    COMPONENT.ProfileContactDetailsIconItemComponent,
    COMPONENT.ViewAllProfileContactDetailsComponent,
    COMPONENT.EpContactListDropdownComponent,
    COMPONENT.EpContactListItemComponent,
    COMPONENT.ProfileSharedListViewComponent,
    COMPONENT.IntroductoryVideoComponent,
    COMPONENT.ClickableCardItemComponent,
    COMPONENT.HeaderComponent,
    COMPONENT.GenericSelectDropdownComponent,
    COMPONENT.CongratulationsCardComponent,
    COMPONENT.UserInfoCardComponent,
    COMPONENT.InstituteInfoCardComponent,
    COMPONENT.ConfirmationPopupComponent,
    COMPONENT.SelectPrivacyDropdownComponent,
    COMPONENT.ContactTypesDropdownComponent,
    COMPONENT.PrivacyButtonComponent,
    COMPONENT.EditAccomplishmentComponent,
    COMPONENT.AddAttachmentsSectionComponent,
    COMPONENT.MyDocsEditComponent,
    COMPONENT.AllTagsModalComponent,
    COMPONENT.TestShowPopupComponent,
    COMPONENT.EditProfileContactDetailsComponent,
    COMPONENT.EpContactListDropdownComponent,
    COMPONENT.EpContactListItemComponent,
    COMPONENT.ProfileContactDetailsIconItemComponent,
    COMPONENT.ViewAllProfileContactDetailsComponent,
    COMPONENT.PhoneCodePickerSelectorComponent,
    COMPONENT.GenericAllTagsViewComponent,
    COMPONENT.AllCommentsComponent,
    COMPONENT.CampusesComponent,
    COMPONENT.EnglishQualificationComponent,
    COMPONENT.FaqComponent,
    COMPONENT.VideoSliderComponent,
    COMPONENT.RecommendedCoursesComponent,
    COMPONENT.RecommendedJobsComponent,
    COMPONENT.AdmissionCardComponent,
    COMPONENT.IonRadioCheckboxSkeletonLoaderComponent,
    COMPONENT.JobDetailsComponent,
    COMPONENT.JobDescriptionPreviewComponent,
    COMPONENT.PerCarTestsComponent,
    COMPONENT.PhotosVideoComponent,
    COMPONENT.UserSearchListComponent,
    // Jobs
    COMPONENT.ApplyingForComponent,
    COMPONENT.CreateJobCardsComponent,
    COMPONENT.CreateJobComponent,
    COMPONENT.ProfileAttachedComponent,
    COMPONENT.ProfileAttachFullComponent,
    COMPONENT.AddCoverLetterComponent,
    COMPONENT.AddCoverLetterFullComponent,
    COMPONENT.WorkAvailabilityMatchComponent,
    COMPONENT.SkillsRequirementMatchComponent,
    COMPONENT.IntroductoryVideoApplyComponent,
    COMPONENT.DistanceWillingTravelMatchComponent,
    COMPONENT.IntroductoryVideoSectionComponent,
    COMPONENT.QuestionsAskedByCompanyComponent,
    COMPONENT.UploadYourCertificateComponent,
    COMPONENT.ConfirmationOfDetailsComponent,
    COMPONENT.ConfirmationWorkAvailabilityMatchComponent,
    COMPONENT.UploadVideoPopupComponent,
    COMPONENT.SelectVideoFromProfileComponent,
    COMPONENT.ConfirmationSkillsRequirementsComponent,
    COMPONENT.ConfirmationVideosComponent,
    COMPONENT.ConfirmationDistanceTravelComponent,
    COMPONENT.CompanyQuestionsConfirmationComponent,
    COMPONENT.ConfirmationCertificationListComponent,
    COMPONENT.ApplicationCompletedComponent,
    COMPONENT.VideoApplicationsSectionsComponent
  ],
  entryComponents: [
    // Generic Components
    COMPONENT.HeaderHomeComponent,
    COMPONENT.ContactdetailsComponent,
    COMPONENT.DurationFilterComponent,
    COMPONENT.VideosComponent,
    COMPONENT.CcFormFinalSlideComponent,
    COMPONENT.CcFormLogoSlideComponent,
    COMPONENT.ProviderCodeComponent,
    COMPONENT.CcWorkingHoursComponent,
    COMPONENT.CompanyProfileVerificationComponent,
    COMPONENT.GenericSingleSelectSearchComponent,
    COMPONENT.GenericBackConfirmationComponent,
    COMPONENT.GenericDescriptionComponent,
    COMPONENT.GenericDeleteConfirmationComponent,
    COMPONENT.GenericIonSearchbarComponent,
    COMPONENT.GenericSearchableRadioSelectionComponent,
    COMPONENT.EditCoverPhotoComponent,
    COMPONENT.EditProfilePhotoComponent,
    COMPONENT.PeopleMayYouKnowComponent,
    COMPONENT.LevelListMultipleComponent,
    COMPONENT.GalleryComponent,
    COMPONENT.CommentsComponent,
    COMPONENT.ViewImageComponent,
    COMPONENT.HeaderComponent,
    COMPONENT.InterestedHobbiesEditComponent,
    COMPONENT.SkillsListComponent,
    COMPONENT.SliderScreensComponent,

    COMPONENT.LocationAutocompleteComponent,
    COMPONENT.PhoneCodePickerComponent,
    COMPONENT.PhoneCodePickerSelectorComponent,
    COMPONENT.ReadAllReviewComponent,
    COMPONENT.WriteAReviewComponent,
    COMPONENT.WriteAReviewNextComponent,
    COMPONENT.AnyDateDaysComponent,
    COMPONENT.AccordionsComponent,
    COMPONENT.PopupsSkeltonLoadersComponent,
    COMPONENT.RatingStarsComponent,
    COMPONENT.CourseCardComponent,
    COMPONENT.CoursesCardsComponent,
    COMPONENT.ScholarshipsCardsComponent,
    COMPONENT.CompanyCardsComponent,
    COMPONENT.DocumentsComponent,
    COMPONENT.UsersRecommendationsComponent,
    COMPONENT.UserFindMeComponent,
    COMPONENT.NearestCourseMapComponent,
    COMPONENT.MapViewCourseComponent,
    COMPONENT.MapViewListComponent,
    COMPONENT.EstimateCostLivingComponent,
    COMPONENT.MapViewComponent,
    COMPONENT.PriceSummaryComponent,
    COMPONENT.DayOfWeekComponent,
    COMPONENT.VideoFullViewComponent,
    COMPONENT.AddToProfileComponent,
    COMPONENT.AddToProfileItemComponent,
    COMPONENT.SeeMoreParaComponent,
    COMPONENT.AssociatedAuthorsInfoComponent,
    COMPONENT.EditEnglishQualificationComponent,
    COMPONENT.DeleteEditItemComponent,
    COMPONENT.ProfileStatusModalComponent,
    COMPONENT.AboutusComponent,
    COMPONENT.PickInstitutionCompanyComponent,
    COMPONENT.CreateCompanyInstituteInfoComponent,
    COMPONENT.CourseInfoPopupComponent,

    // Customize Gallery
    COMPONENT.LoadGalleryComponent,
    COMPONENT.GenericCourseSearchMultipleComponent,
    COMPONENT.GenericFacultySearchMultipleComponent,
    COMPONENT.GenderCommonDropdownComponent,
    COMPONENT.GenericDescriptionComponent,
    COMPONENT.GenericIonSearchbarComponent,
    COMPONENT.GenericMultiSearchableRadioSelectionComponent,
    COMPONENT.UsersComponent,
    COMPONENT.SideInfoCardsComponent,
    // PROFILE SHARED COMPONENTS
    COMPONENT.ProfileHeaderComponent,
    COMPONENT.ProfileVideosComponent,
    COMPONENT.ProfileStatusComponent,
    COMPONENT.ProfileInfoWrapSliderComponent,
    COMPONENT.ProfileAddToProfileComponent,
    COMPONENT.ProfileContactDetailsComponent,
    COMPONENT.EditProfileContactDetailsComponent,
    COMPONENT.ProfileContactDetailsIconItemComponent,
    COMPONENT.ViewAllProfileContactDetailsComponent,
    COMPONENT.EpContactListDropdownComponent,
    COMPONENT.EpContactListItemComponent,
    COMPONENT.ProfileSharedListViewComponent,
    COMPONENT.IntroductoryVideoComponent,
    COMPONENT.ClickableCardItemComponent,
    COMPONENT.HeaderComponent,
    COMPONENT.GenericSelectDropdownComponent,
    COMPONENT.CongratulationsCardComponent,
    COMPONENT.UserInfoCardComponent,
    COMPONENT.InstituteInfoCardComponent,
    COMPONENT.ConfirmationPopupComponent,
    COMPONENT.SelectPrivacyDropdownComponent,
    COMPONENT.ContactTypesDropdownComponent,
    COMPONENT.PrivacyButtonComponent,
    COMPONENT.EditAccomplishmentComponent,
    COMPONENT.AddAttachmentsSectionComponent,
    COMPONENT.MyDocsEditComponent,
    COMPONENT.AllTagsModalComponent,

    COMPONENT.TestShowPopupComponent,
    COMPONENT.EditProfileContactDetailsComponent,
    COMPONENT.EpContactListDropdownComponent,
    COMPONENT.EpContactListItemComponent,
    COMPONENT.ProfileContactDetailsIconItemComponent,
    COMPONENT.ViewAllProfileContactDetailsComponent,
    COMPONENT.PhoneCodePickerSelectorComponent,
    COMPONENT.GenericAllTagsViewComponent,
    COMPONENT.AllCommentsComponent,
    COMPONENT.CampusesComponent,
    COMPONENT.EnglishQualificationComponent,
    COMPONENT.FaqComponent,
    COMPONENT.VideoSliderComponent,
    COMPONENT.RecommendedCoursesComponent,
    COMPONENT.RecommendedJobsComponent,
    COMPONENT.AdmissionCardComponent,
    COMPONENT.IonRadioCheckboxSkeletonLoaderComponent,
    COMPONENT.JobDetailsComponent,
    COMPONENT.JobDescriptionPreviewComponent,
    COMPONENT.PerCarTestsComponent,
    COMPONENT.PhotosVideoComponent,
    COMPONENT.UserSearchListComponent,
    COMPONENT.ApplyingForComponent,
    COMPONENT.CreateJobCardsComponent,
    COMPONENT.CreateJobComponent,
    COMPONENT.ProfileAttachedComponent,
    COMPONENT.ProfileAttachFullComponent,
    COMPONENT.AddCoverLetterComponent,
    COMPONENT.AddCoverLetterFullComponent,
    COMPONENT.WorkAvailabilityMatchComponent,
    COMPONENT.SkillsRequirementMatchComponent,
    COMPONENT.IntroductoryVideoApplyComponent,
    COMPONENT.DistanceWillingTravelMatchComponent,
    COMPONENT.IntroductoryVideoSectionComponent,
    COMPONENT.QuestionsAskedByCompanyComponent,
    COMPONENT.UploadYourCertificateComponent,
    COMPONENT.ConfirmationOfDetailsComponent,
    COMPONENT.ConfirmationWorkAvailabilityMatchComponent,
    COMPONENT.UploadVideoPopupComponent,
    COMPONENT.SelectVideoFromProfileComponent,
    COMPONENT.ConfirmationSkillsRequirementsComponent,
    COMPONENT.ConfirmationVideosComponent,
    COMPONENT.ConfirmationDistanceTravelComponent,
    COMPONENT.CompanyQuestionsConfirmationComponent,
    COMPONENT.ConfirmationCertificationListComponent,
    COMPONENT.ApplicationCompletedComponent,
    COMPONENT.VideoApplicationsSectionsComponent

  ],
  exports: [
    YuzeeCommonModule,
    BoldPipe,
    CDVPhotoLibraryPipe,
    ShortNumberPipe,
    LongPressDirective,
    WhiteSpaceRestrictionDirective,
    InputNumberValidation,
    Autosize,
    TranslateModule,
    BarRatingModule,
    CKEditorModule,
    // Generic Components
    COMPONENT.HeaderHomeComponent,
    COMPONENT.ContactdetailsComponent,
    COMPONENT.DurationFilterComponent,
    COMPONENT.VideosComponent,
    COMPONENT.CcFormFinalSlideComponent,
    COMPONENT.CcFormLogoSlideComponent,
    COMPONENT.ProviderCodeComponent,
    COMPONENT.CcWorkingHoursComponent,
    COMPONENT.CompanyProfileVerificationComponent,
    COMPONENT.GenericSingleSelectSearchComponent,
    COMPONENT.GenericBackConfirmationComponent,
    COMPONENT.GenericDescriptionComponent,
    COMPONENT.GenericDeleteConfirmationComponent,
    COMPONENT.GenericIonSearchbarComponent,
    COMPONENT.GenericSearchableRadioSelectionComponent,
    COMPONENT.EditCoverPhotoComponent,
    COMPONENT.EditProfilePhotoComponent,
    COMPONENT.PeopleMayYouKnowComponent,
    COMPONENT.LevelListMultipleComponent,
    COMPONENT.GalleryComponent,
    COMPONENT.CommentsComponent,
    COMPONENT.ViewImageComponent,
    COMPONENT.HeaderComponent,
    COMPONENT.InterestedHobbiesEditComponent,
    COMPONENT.SkillsListComponent,
    COMPONENT.SliderScreensComponent,
    COMPONENT.LocationAutocompleteComponent,
    COMPONENT.PhoneCodePickerComponent,
    COMPONENT.PhoneCodePickerSelectorComponent,
    COMPONENT.ReadAllReviewComponent,
    COMPONENT.WriteAReviewComponent,
    COMPONENT.WriteAReviewNextComponent,
    COMPONENT.AnyDateDaysComponent,
    COMPONENT.AccordionsComponent,
    COMPONENT.PopupsSkeltonLoadersComponent,
    COMPONENT.RatingStarsComponent,
    COMPONENT.CourseCardComponent,
    COMPONENT.CoursesCardsComponent,
    COMPONENT.ScholarshipsCardsComponent,
    COMPONENT.CompanyCardsComponent,
    COMPONENT.DocumentsComponent,
    COMPONENT.UsersRecommendationsComponent,
    COMPONENT.UserFindMeComponent,
    COMPONENT.NearestCourseMapComponent,
    COMPONENT.MapViewCourseComponent,
    COMPONENT.MapViewListComponent,
    COMPONENT.EstimateCostLivingComponent,
    COMPONENT.MapViewComponent,
    COMPONENT.PriceSummaryComponent,
    COMPONENT.DayOfWeekComponent,
    COMPONENT.VideoFullViewComponent,
    COMPONENT.AddToProfileComponent,
    COMPONENT.AddToProfileItemComponent,
    COMPONENT.SeeMoreParaComponent,
    COMPONENT.AssociatedAuthorsInfoComponent,
    COMPONENT.EditEnglishQualificationComponent,
    COMPONENT.DeleteEditItemComponent,
    COMPONENT.ProfileStatusModalComponent,
    COMPONENT.AboutusComponent,
    COMPONENT.PickInstitutionCompanyComponent,
    COMPONENT.CreateCompanyInstituteInfoComponent,
    COMPONENT.CourseInfoPopupComponent,

    // Customize Gallery
    COMPONENT.LoadGalleryComponent,
    COMPONENT.GenericCourseSearchMultipleComponent,
    COMPONENT.GenericFacultySearchMultipleComponent,
    COMPONENT.GenderCommonDropdownComponent,
    COMPONENT.GenericDescriptionComponent,
    COMPONENT.GenericIonSearchbarComponent,
    COMPONENT.GenericMultiSearchableRadioSelectionComponent,
    COMPONENT.UsersComponent,
    COMPONENT.SideInfoCardsComponent,
    // PROFILE SHARED COMPONENTS
    COMPONENT.ProfileHeaderComponent,
    COMPONENT.ProfileVideosComponent,
    COMPONENT.ProfileStatusComponent,
    COMPONENT.ProfileInfoWrapSliderComponent,
    COMPONENT.ProfileAddToProfileComponent,
    COMPONENT.ProfileContactDetailsComponent,
    COMPONENT.EditProfileContactDetailsComponent,
    COMPONENT.ProfileContactDetailsIconItemComponent,
    COMPONENT.ViewAllProfileContactDetailsComponent,
    COMPONENT.EpContactListDropdownComponent,
    COMPONENT.EpContactListItemComponent,
    COMPONENT.ProfileSharedListViewComponent,
    COMPONENT.IntroductoryVideoComponent,
    COMPONENT.ClickableCardItemComponent,
    COMPONENT.HeaderComponent,
    COMPONENT.GenericSelectDropdownComponent,
    // offer Preview

    COMPONENT.CongratulationsCardComponent,
    COMPONENT.UserInfoCardComponent,
    COMPONENT.InstituteInfoCardComponent,
    COMPONENT.ConfirmationPopupComponent,
    COMPONENT.SelectPrivacyDropdownComponent,
    COMPONENT.ContactTypesDropdownComponent,
    COMPONENT.PrivacyButtonComponent,
    COMPONENT.EditAccomplishmentComponent,
    COMPONENT.AddAttachmentsSectionComponent,
    COMPONENT.MyDocsEditComponent,
    COMPONENT.AllTagsModalComponent,

    COMPONENT.TestShowPopupComponent,
    COMPONENT.EditProfileContactDetailsComponent,
    COMPONENT.EpContactListDropdownComponent,
    COMPONENT.EpContactListItemComponent,
    COMPONENT.ProfileContactDetailsIconItemComponent,
    COMPONENT.ViewAllProfileContactDetailsComponent,
    COMPONENT.PhoneCodePickerSelectorComponent,
    COMPONENT.GenericAllTagsViewComponent,
    COMPONENT.AllCommentsComponent,
    COMPONENT.CampusesComponent,
    COMPONENT.EnglishQualificationComponent,
    COMPONENT.FaqComponent,
    COMPONENT.VideoSliderComponent,
    COMPONENT.RecommendedCoursesComponent,
    COMPONENT.RecommendedJobsComponent,
    COMPONENT.AdmissionCardComponent,
    COMPONENT.IonRadioCheckboxSkeletonLoaderComponent,
    COMPONENT.JobDetailsComponent,
    COMPONENT.JobDescriptionPreviewComponent,
    COMPONENT.PerCarTestsComponent,
    COMPONENT.PhotosVideoComponent,
    COMPONENT.UserSearchListComponent,
    COMPONENT.ApplyingForComponent,
    COMPONENT.CreateJobCardsComponent,
    COMPONENT.CreateJobComponent,
    COMPONENT.ProfileAttachedComponent,
    COMPONENT.ProfileAttachFullComponent,
    COMPONENT.AddCoverLetterComponent,
    COMPONENT.AddCoverLetterFullComponent,
    COMPONENT.WorkAvailabilityMatchComponent,
    COMPONENT.SkillsRequirementMatchComponent,
    COMPONENT.IntroductoryVideoApplyComponent,
    COMPONENT.DistanceWillingTravelMatchComponent,
    COMPONENT.IntroductoryVideoSectionComponent,
    COMPONENT.QuestionsAskedByCompanyComponent,
    COMPONENT.UploadYourCertificateComponent,
    COMPONENT.ConfirmationOfDetailsComponent,
    COMPONENT.ConfirmationWorkAvailabilityMatchComponent,
    COMPONENT.UploadVideoPopupComponent,
    COMPONENT.SelectVideoFromProfileComponent,
    COMPONENT.ConfirmationSkillsRequirementsComponent,
    COMPONENT.ConfirmationVideosComponent,
    COMPONENT.ConfirmationDistanceTravelComponent,
    COMPONENT.CompanyQuestionsConfirmationComponent,
    COMPONENT.ConfirmationCertificationListComponent,
    COMPONENT.ApplicationCompletedComponent,
    COMPONENT.VideoApplicationsSectionsComponent
  ],
})
export class AppSharedModule {
  static forRoot() {
    return {
      ngModule: AppSharedModule,
    };
  }
}

