export * from './scholarships-list/scholarships-list.component';
export * from './all-scholarships/all-scholarships.component';
export * from './view-all-scholarships/view-all-scholarships.component';
export * from './deadline-date-popup/deadline-date-popup.component';
export * from './view-all-scholarships-details/view-all-scholarships-details.component';
export * from './all-scholarships/scholarships-list-item/scholarships-list-item.component';
export * from './view-all-scholarships-details/scholorship-details-about/scholorship-details-about.component'
export * from './view-all-scholarships-details/scholorship-details-other/scholorship-details-other.component'
export * from './view-all-scholarships-details/scholorship-details-about-points/scholorship-details-about-points.component'
export * from './view-all-scholarships-details/scholorship-details-requirements/scholorship-details-requirements.component'
export * from './view-all-scholarships-details/scholorship-details-about-keypoints/scholorship-details-about-keypoints.component';